# Header
menu:
  piratf: /
  归档: /archives
  # 实验室: /_special
rss: /atom.xml
favicon: /favicon.png
subtitle_show: true

# Main
duoshuo_shortname: piratf
duoshuo_home: true

#### Analytics  
cnzz: true 